#!/usr/bin/env ruby
# coding: utf-8
require 'fest'
system(ARGF.argv.join(' '))

loop do
  begin
    Process.getpgid($?.pid)
  rescue Errno::ESRCH
    @fest = Fest.new
    @fest.say('Программа завершила работу')
    system("/usr/bin/notify-send '     Exit:  #{ARGF.argv.join(' ')}' -t 5")
    break
  end
end
