#!/bin/bash

branch () {
    if [[ $1 ]]; then
        git checkout -f master || git checkout -fb master
        git pull origin master
        git checkout "$1" || git checkout -b "$1"
        git pull origin -f "$1"
        init && up
    fi
}

up () {
    init && time docker-compose build app db
    docker-compose up
}

init () {
    status=$(systemctl status docker | awk '/Active:/{printf $2}')
    if [ "$status" != 'active' ]; then
        sudo systemctl start docker
    fi
}

console () {
    docker exec -it $(docker-compose ps | awk '/app/{printf $1}') /bin/bash
}

help () {
    echo "Usage:"
    echo "      $0"
    echo "Main options:"
    echo "    s  up         : project up"
    echo "    b  branch     : change branch"
    echo "    c  console    : rails console "
    echo "    h  help       : print help and exit"
}

case $1 in
    s|up)        up                        ;;
    b|branch)    branch $2                 ;;
    c|console)   console                   ;;
    h|help)      help                      ;;
    *)
        echo "'$1' is not valid command"
        help
        ;;
esac

exit 0
