version: '2'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/web
    depends_on:
      - db
    env_file:
      - $HOME/.docker/hopox/db.env
  db:
    image: sameersbn/postgresql
    ports:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - $HOME/.docker/hopox/db.env
volumes:
  db_data:
