#!/bin/sh

# config
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config auto_alternate true
bspc config history_aware_focus true

# desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# rules
bspc rule -a '*' state=fullscreen
bspc rule -a Firefox desktop=^1 state=fullscreen
bspc rule -a "*hromium*" desktop=^5 state=fullscreen
bspc rule -a skype desktop=^4 state=floating
bspc rule -a "xterm, Xterm" state=fullscreen
